version: '3'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:8.0.23
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  backend:
    build: ./
    container_name: backend
    networks:
      - app-network
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  frontend:
    build: ../vkr-orlova/
    container_name: frontend
    networks:
      - app-network
    ports:
      - 4200:96
    links:
      - backend

volumes:
  dbdata:


