version: '3'
services:

  db:
    image: mysql:8.0.23
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  backend:
    build: ./
    container_name: backend
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - db

#  kanban-ui:
#    build: ./kanban-ui
#    container_name: kanban-ui
#    ports:
#      - 4200:80
#    links:
#      - kanban-app

volumes:
  dbdata:


