require('./insert_disciplines_teachers');
require('./insert_disciplines');
require('./insert_groups');
require('./insert_jobs');
require('./insert_marks');
require('./insert_students');
require('./insert_students_disciplines');
require('./insert_teachers');
require('./insert_modules');
